/*
 * This file is generated by jOOQ.
 */
package info.galudisu.comic.model;


import info.galudisu.comic.model.tables.Accounts;
import info.galudisu.comic.model.tables.Clients;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comic extends SchemaImpl {

    private static final long serialVersionUID = 200140029;

    public static final Comic COMIC = new Comic();

    public final Accounts ACCOUNTS = info.galudisu.comic.model.tables.Accounts.ACCOUNTS;

    public final Clients CLIENTS = info.galudisu.comic.model.tables.Clients.CLIENTS;

    private Comic() {
        super("comic", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accounts.ACCOUNTS,
            Clients.CLIENTS);
    }
}
