/*
 * This file is generated by jOOQ.
 */
package info.galudisu.comic.model;


import info.galudisu.comic.model.tables.Account;
import info.galudisu.comic.model.tables.AccountRole;
import info.galudisu.comic.model.tables.Clients;
import info.galudisu.comic.model.tables.Permission;
import info.galudisu.comic.model.tables.Role;
import info.galudisu.comic.model.tables.RolePermission;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comic extends SchemaImpl {

    private static final long serialVersionUID = -1672846887;

    public static final Comic COMIC = new Comic();

    public final Account ACCOUNT = info.galudisu.comic.model.tables.Account.ACCOUNT;

    public final AccountRole ACCOUNT_ROLE = info.galudisu.comic.model.tables.AccountRole.ACCOUNT_ROLE;

    public final Clients CLIENTS = info.galudisu.comic.model.tables.Clients.CLIENTS;

    public final Permission PERMISSION = info.galudisu.comic.model.tables.Permission.PERMISSION;

    public final Role ROLE = info.galudisu.comic.model.tables.Role.ROLE;

    public final RolePermission ROLE_PERMISSION = info.galudisu.comic.model.tables.RolePermission.ROLE_PERMISSION;

    private Comic() {
        super("comic", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            AccountRole.ACCOUNT_ROLE,
            Clients.CLIENTS,
            Permission.PERMISSION,
            Role.ROLE,
            RolePermission.ROLE_PERMISSION);
    }
}
