/*
 * This file is generated by jOOQ.
 */
package info.galudisu.comic.model;


import info.galudisu.comic.model.tables.Accounts;
import info.galudisu.comic.model.tables.Clients;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNTS_ACCOUNT_SALT_IDX = Indexes0.ACCOUNTS_ACCOUNT_SALT_IDX;
    public static final Index ACCOUNTS_ACCOUNT_USERNAME_IDX = Indexes0.ACCOUNTS_ACCOUNT_USERNAME_IDX;
    public static final Index ACCOUNTS_ID = Indexes0.ACCOUNTS_ID;
    public static final Index ACCOUNTS_PRIMARY = Indexes0.ACCOUNTS_PRIMARY;
    public static final Index ACCOUNTS_SALT = Indexes0.ACCOUNTS_SALT;
    public static final Index ACCOUNTS_UID = Indexes0.ACCOUNTS_UID;
    public static final Index CLIENTS_CLIENT_CLIENT_ID_IDX = Indexes0.CLIENTS_CLIENT_CLIENT_ID_IDX;
    public static final Index CLIENTS_CLIENT_CLIENT_SECRET_IDX = Indexes0.CLIENTS_CLIENT_CLIENT_SECRET_IDX;
    public static final Index CLIENTS_CLIENT_ID = Indexes0.CLIENTS_CLIENT_ID;
    public static final Index CLIENTS_CLIENT_SECRET = Indexes0.CLIENTS_CLIENT_SECRET;
    public static final Index CLIENTS_ID = Indexes0.CLIENTS_ID;
    public static final Index CLIENTS_OWNER_ID = Indexes0.CLIENTS_OWNER_ID;
    public static final Index CLIENTS_PRIMARY = Indexes0.CLIENTS_PRIMARY;
    public static final Index CLIENTS_UID = Indexes0.CLIENTS_UID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNTS_ACCOUNT_SALT_IDX = Internal.createIndex("ACCOUNT_SALT_IDX", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.SALT }, true);
        public static Index ACCOUNTS_ACCOUNT_USERNAME_IDX = Internal.createIndex("ACCOUNT_USERNAME_IDX", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.USERNAME }, true);
        public static Index ACCOUNTS_ID = Internal.createIndex("ID", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.ID }, true);
        public static Index ACCOUNTS_PRIMARY = Internal.createIndex("PRIMARY", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.ID }, true);
        public static Index ACCOUNTS_SALT = Internal.createIndex("SALT", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.SALT }, true);
        public static Index ACCOUNTS_UID = Internal.createIndex("UID", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.UID }, true);
        public static Index CLIENTS_CLIENT_CLIENT_ID_IDX = Internal.createIndex("CLIENT_CLIENT_ID_IDX", Clients.CLIENTS, new OrderField[] { Clients.CLIENTS.CLIENT_ID }, true);
        public static Index CLIENTS_CLIENT_CLIENT_SECRET_IDX = Internal.createIndex("CLIENT_CLIENT_SECRET_IDX", Clients.CLIENTS, new OrderField[] { Clients.CLIENTS.CLIENT_SECRET }, true);
        public static Index CLIENTS_CLIENT_ID = Internal.createIndex("CLIENT_ID", Clients.CLIENTS, new OrderField[] { Clients.CLIENTS.CLIENT_ID }, true);
        public static Index CLIENTS_CLIENT_SECRET = Internal.createIndex("CLIENT_SECRET", Clients.CLIENTS, new OrderField[] { Clients.CLIENTS.CLIENT_SECRET }, true);
        public static Index CLIENTS_ID = Internal.createIndex("ID", Clients.CLIENTS, new OrderField[] { Clients.CLIENTS.ID }, true);
        public static Index CLIENTS_OWNER_ID = Internal.createIndex("OWNER_ID", Clients.CLIENTS, new OrderField[] { Clients.CLIENTS.OWNER_ID }, true);
        public static Index CLIENTS_PRIMARY = Internal.createIndex("PRIMARY", Clients.CLIENTS, new OrderField[] { Clients.CLIENTS.ID }, true);
        public static Index CLIENTS_UID = Internal.createIndex("UID", Clients.CLIENTS, new OrderField[] { Clients.CLIENTS.UID }, true);
    }
}
