/*
 * This file is generated by jOOQ.
 */
package info.galudisu.comic.model;


import info.galudisu.comic.model.tables.RolesPermissions;
import info.galudisu.comic.model.tables.UserRoles;
import info.galudisu.comic.model.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ROLES_PERMISSIONS_ID = Indexes0.ROLES_PERMISSIONS_ID;
    public static final Index ROLES_PERMISSIONS_PRIMARY = Indexes0.ROLES_PERMISSIONS_PRIMARY;
    public static final Index ROLES_PERMISSIONS_ROLES_PERMISSIONS_PERMISSION_IDX = Indexes0.ROLES_PERMISSIONS_ROLES_PERMISSIONS_PERMISSION_IDX;
    public static final Index ROLES_PERMISSIONS_ROLES_PERMISSIONS_ROLE_NAME_IDX = Indexes0.ROLES_PERMISSIONS_ROLES_PERMISSIONS_ROLE_NAME_IDX;
    public static final Index ROLES_PERMISSIONS_UID = Indexes0.ROLES_PERMISSIONS_UID;
    public static final Index USER_ROLES_ID = Indexes0.USER_ROLES_ID;
    public static final Index USER_ROLES_PRIMARY = Indexes0.USER_ROLES_PRIMARY;
    public static final Index USER_ROLES_UID = Indexes0.USER_ROLES_UID;
    public static final Index USER_ROLES_USER_ROLES_ROLE_NAME_IDX = Indexes0.USER_ROLES_USER_ROLES_ROLE_NAME_IDX;
    public static final Index USER_ROLES_USER_ROLES_USERNAME_IDX = Indexes0.USER_ROLES_USER_ROLES_USERNAME_IDX;
    public static final Index USERS_ID = Indexes0.USERS_ID;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index USERS_UID = Indexes0.USERS_UID;
    public static final Index USERS_USERS_USERNAME_IDX = Indexes0.USERS_USERS_USERNAME_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ROLES_PERMISSIONS_ID = Internal.createIndex("ID", RolesPermissions.ROLES_PERMISSIONS, new OrderField[] { RolesPermissions.ROLES_PERMISSIONS.ID }, true);
        public static Index ROLES_PERMISSIONS_PRIMARY = Internal.createIndex("PRIMARY", RolesPermissions.ROLES_PERMISSIONS, new OrderField[] { RolesPermissions.ROLES_PERMISSIONS.ID }, true);
        public static Index ROLES_PERMISSIONS_ROLES_PERMISSIONS_PERMISSION_IDX = Internal.createIndex("ROLES_PERMISSIONS_PERMISSION_IDX", RolesPermissions.ROLES_PERMISSIONS, new OrderField[] { RolesPermissions.ROLES_PERMISSIONS.PERMISSION }, true);
        public static Index ROLES_PERMISSIONS_ROLES_PERMISSIONS_ROLE_NAME_IDX = Internal.createIndex("ROLES_PERMISSIONS_ROLE_NAME_IDX", RolesPermissions.ROLES_PERMISSIONS, new OrderField[] { RolesPermissions.ROLES_PERMISSIONS.ROLE_NAME }, true);
        public static Index ROLES_PERMISSIONS_UID = Internal.createIndex("UID", RolesPermissions.ROLES_PERMISSIONS, new OrderField[] { RolesPermissions.ROLES_PERMISSIONS.UID }, true);
        public static Index USER_ROLES_ID = Internal.createIndex("ID", UserRoles.USER_ROLES, new OrderField[] { UserRoles.USER_ROLES.ID }, true);
        public static Index USER_ROLES_PRIMARY = Internal.createIndex("PRIMARY", UserRoles.USER_ROLES, new OrderField[] { UserRoles.USER_ROLES.ID }, true);
        public static Index USER_ROLES_UID = Internal.createIndex("UID", UserRoles.USER_ROLES, new OrderField[] { UserRoles.USER_ROLES.UID }, true);
        public static Index USER_ROLES_USER_ROLES_ROLE_NAME_IDX = Internal.createIndex("USER_ROLES_ROLE_NAME_IDX", UserRoles.USER_ROLES, new OrderField[] { UserRoles.USER_ROLES.ROLE_NAME }, true);
        public static Index USER_ROLES_USER_ROLES_USERNAME_IDX = Internal.createIndex("USER_ROLES_USERNAME_IDX", UserRoles.USER_ROLES, new OrderField[] { UserRoles.USER_ROLES.USERNAME }, true);
        public static Index USERS_ID = Internal.createIndex("ID", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_UID = Internal.createIndex("UID", Users.USERS, new OrderField[] { Users.USERS.UID }, true);
        public static Index USERS_USERS_USERNAME_IDX = Internal.createIndex("USERS_USERNAME_IDX", Users.USERS, new OrderField[] { Users.USERS.USERNAME }, true);
    }
}
