/*
 * This file is generated by jOOQ.
 */
package info.galudisu.comic.model;


import info.galudisu.comic.model.tables.Accounts;
import info.galudisu.comic.model.tables.Clients;

import javax.annotation.Generated;


@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    public static final Accounts ACCOUNTS = info.galudisu.comic.model.tables.Accounts.ACCOUNTS;

    public static final Clients CLIENTS = info.galudisu.comic.model.tables.Clients.CLIENTS;
}
