---
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql_8_0
  application:
    name: "comic-cloud-admin"
  flyway:
    baseline-on-migrate: true

  jackson:
    default-property-inclusion: non_null
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
---