---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/comic-cloud-admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: false
  redis:
    host: localhost
    port: 6379
    password:
---