/*
 * This file is generated by jOOQ.
 */
package info.galudisu.comic.model.tables.records;


import info.galudisu.comic.model.tables.Clients;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientsRecord extends UpdatableRecordImpl<ClientsRecord> implements Record7<Integer, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -345670457;

    /**
     * Setter for <code>comic.clients.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>comic.clients.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>comic.clients.UID</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>comic.clients.UID</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>comic.clients.OWNER_ID</code>.
     */
    public void setOwnerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>comic.clients.OWNER_ID</code>.
     */
    public String getOwnerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>comic.clients.CLIENT_ID</code>.
     */
    public void setClientId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>comic.clients.CLIENT_ID</code>.
     */
    public String getClientId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>comic.clients.CLIENT_SECRET</code>.
     */
    public void setClientSecret(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>comic.clients.CLIENT_SECRET</code>.
     */
    public String getClientSecret() {
        return (String) get(4);
    }

    /**
     * Setter for <code>comic.clients.REDIRECT_URI</code>.
     */
    public void setRedirectUri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>comic.clients.REDIRECT_URI</code>.
     */
    public String getRedirectUri() {
        return (String) get(5);
    }

    /**
     * Setter for <code>comic.clients.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>comic.clients.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Clients.CLIENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Clients.CLIENTS.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Clients.CLIENTS.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Clients.CLIENTS.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Clients.CLIENTS.CLIENT_SECRET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Clients.CLIENTS.REDIRECT_URI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Clients.CLIENTS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getClientSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRedirectUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getClientSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRedirectUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientsRecord value2(String value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientsRecord value3(String value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientsRecord value4(String value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientsRecord value5(String value) {
        setClientSecret(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientsRecord value6(String value) {
        setRedirectUri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientsRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientsRecord
     */
    public ClientsRecord() {
        super(Clients.CLIENTS);
    }

    /**
     * Create a detached, initialised ClientsRecord
     */
    public ClientsRecord(Integer id, String uid, String ownerId, String clientId, String clientSecret, String redirectUri, Timestamp createdAt) {
        super(Clients.CLIENTS);

        set(0, id);
        set(1, uid);
        set(2, ownerId);
        set(3, clientId);
        set(4, clientSecret);
        set(5, redirectUri);
        set(6, createdAt);
    }
}
