/*
 * This file is generated by jOOQ.
 */
package info.galudisu.comic.model.tables.records;


import info.galudisu.comic.model.tables.Clients;

import java.time.Instant;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientsRecord extends UpdatableRecordImpl<ClientsRecord> implements Record10<Integer, String, String, String, String, String, Instant, String, Instant, String> {

    private static final long serialVersionUID = 974712966;

    public void setId(Integer value) {
        set(0, value);
    }

    public Integer getId() {
        return (Integer) get(0);
    }

    public void setUid(String value) {
        set(1, value);
    }

    public String getUid() {
        return (String) get(1);
    }

    public void setOwnerId(String value) {
        set(2, value);
    }

    public String getOwnerId() {
        return (String) get(2);
    }

    public void setClientId(String value) {
        set(3, value);
    }

    public String getClientId() {
        return (String) get(3);
    }

    public void setClientSecret(String value) {
        set(4, value);
    }

    public String getClientSecret() {
        return (String) get(4);
    }

    public void setRedirectUri(String value) {
        set(5, value);
    }

    public String getRedirectUri() {
        return (String) get(5);
    }

    public void setCreatedAt(Instant value) {
        set(6, value);
    }

    public Instant getCreatedAt() {
        return (Instant) get(6);
    }

    public void setCreatedBy(String value) {
        set(7, value);
    }

    public String getCreatedBy() {
        return (String) get(7);
    }

    public void setUpdatedAt(Instant value) {
        set(8, value);
    }

    public Instant getUpdatedAt() {
        return (Instant) get(8);
    }

    public void setUpdatedBy(String value) {
        set(9, value);
    }

    public String getUpdatedBy() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, String, Instant, String, Instant, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, String, Instant, String, Instant, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Clients.CLIENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Clients.CLIENTS.UID;
    }

    @Override
    public Field<String> field3() {
        return Clients.CLIENTS.OWNER_ID;
    }

    @Override
    public Field<String> field4() {
        return Clients.CLIENTS.CLIENT_ID;
    }

    @Override
    public Field<String> field5() {
        return Clients.CLIENTS.CLIENT_SECRET;
    }

    @Override
    public Field<String> field6() {
        return Clients.CLIENTS.REDIRECT_URI;
    }

    @Override
    public Field<Instant> field7() {
        return Clients.CLIENTS.CREATED_AT;
    }

    @Override
    public Field<String> field8() {
        return Clients.CLIENTS.CREATED_BY;
    }

    @Override
    public Field<Instant> field9() {
        return Clients.CLIENTS.UPDATED_AT;
    }

    @Override
    public Field<String> field10() {
        return Clients.CLIENTS.UPDATED_BY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUid();
    }

    @Override
    public String component3() {
        return getOwnerId();
    }

    @Override
    public String component4() {
        return getClientId();
    }

    @Override
    public String component5() {
        return getClientSecret();
    }

    @Override
    public String component6() {
        return getRedirectUri();
    }

    @Override
    public Instant component7() {
        return getCreatedAt();
    }

    @Override
    public String component8() {
        return getCreatedBy();
    }

    @Override
    public Instant component9() {
        return getUpdatedAt();
    }

    @Override
    public String component10() {
        return getUpdatedBy();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUid();
    }

    @Override
    public String value3() {
        return getOwnerId();
    }

    @Override
    public String value4() {
        return getClientId();
    }

    @Override
    public String value5() {
        return getClientSecret();
    }

    @Override
    public String value6() {
        return getRedirectUri();
    }

    @Override
    public Instant value7() {
        return getCreatedAt();
    }

    @Override
    public String value8() {
        return getCreatedBy();
    }

    @Override
    public Instant value9() {
        return getUpdatedAt();
    }

    @Override
    public String value10() {
        return getUpdatedBy();
    }

    @Override
    public ClientsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ClientsRecord value2(String value) {
        setUid(value);
        return this;
    }

    @Override
    public ClientsRecord value3(String value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public ClientsRecord value4(String value) {
        setClientId(value);
        return this;
    }

    @Override
    public ClientsRecord value5(String value) {
        setClientSecret(value);
        return this;
    }

    @Override
    public ClientsRecord value6(String value) {
        setRedirectUri(value);
        return this;
    }

    @Override
    public ClientsRecord value7(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ClientsRecord value8(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ClientsRecord value9(Instant value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public ClientsRecord value10(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public ClientsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Instant value7, String value8, Instant value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public ClientsRecord() {
        super(Clients.CLIENTS);
    }

    public ClientsRecord(Integer id, String uid, String ownerId, String clientId, String clientSecret, String redirectUri, Instant createdAt, String createdBy, Instant updatedAt, String updatedBy) {
        super(Clients.CLIENTS);

        set(0, id);
        set(1, uid);
        set(2, ownerId);
        set(3, clientId);
        set(4, clientSecret);
        set(5, redirectUri);
        set(6, createdAt);
        set(7, createdBy);
        set(8, updatedAt);
        set(9, updatedBy);
    }
}
