/*
 * This file is generated by jOOQ.
 */
package info.galudisu.comic.model.tables;


import info.galudisu.comic.converter.InstantConverter;
import info.galudisu.comic.model.Comic;
import info.galudisu.comic.model.Indexes;
import info.galudisu.comic.model.Keys;
import info.galudisu.comic.model.tables.records.AccountsRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accounts extends TableImpl<AccountsRecord> {

    private static final long serialVersionUID = -50101968;

    public static final Accounts ACCOUNTS = new Accounts();

    @Override
    public Class<AccountsRecord> getRecordType() {
        return AccountsRecord.class;
    }

    public final TableField<AccountsRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    public final TableField<AccountsRecord, String> UID = createField("UID", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    public final TableField<AccountsRecord, String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false), this, "");

    public final TableField<AccountsRecord, String> PASSWORD = createField("PASSWORD", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false), this, "");

    public final TableField<AccountsRecord, String> SALT = createField("SALT", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false), this, "");

    public final TableField<AccountsRecord, String> EMAIL = createField("EMAIL", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    public final TableField<AccountsRecord, String> PHONE = createField("PHONE", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    public final TableField<AccountsRecord, Instant> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "", new InstantConverter());

    public Accounts() {
        this(DSL.name("accounts"), null);
    }

    public Accounts(String alias) {
        this(DSL.name(alias), ACCOUNTS);
    }

    public Accounts(Name alias) {
        this(alias, ACCOUNTS);
    }

    private Accounts(Name alias, Table<AccountsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Accounts(Name alias, Table<AccountsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Accounts(Table<O> child, ForeignKey<O, AccountsRecord> key) {
        super(child, key, ACCOUNTS);
    }

    @Override
    public Schema getSchema() {
        return Comic.COMIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACCOUNTS_ACCOUNT_SALT_IDX, Indexes.ACCOUNTS_ACCOUNT_USERNAME_IDX, Indexes.ACCOUNTS_ID, Indexes.ACCOUNTS_PRIMARY, Indexes.ACCOUNTS_SALT, Indexes.ACCOUNTS_UID);
    }

    @Override
    public Identity<AccountsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ACCOUNTS;
    }

    @Override
    public UniqueKey<AccountsRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<AccountsRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountsRecord>>asList(Keys.KEY_ACCOUNTS_PRIMARY, Keys.KEY_ACCOUNTS_ID, Keys.KEY_ACCOUNTS_UID, Keys.KEY_ACCOUNTS_ACCOUNT_USERNAME_IDX, Keys.KEY_ACCOUNTS_ACCOUNT_SALT_IDX, Keys.KEY_ACCOUNTS_SALT);
    }

    @Override
    public Accounts as(String alias) {
        return new Accounts(DSL.name(alias), this);
    }

    @Override
    public Accounts as(Name alias) {
        return new Accounts(alias, this);
    }

    @Override
    public Accounts rename(String name) {
        return new Accounts(DSL.name(name), null);
    }

    @Override
    public Accounts rename(Name name) {
        return new Accounts(name, null);
    }
}
